spring.application.name=expense
spring.datasource.url=jdbc:mysql://localhost:3306/expense_sharing
spring.datasource.username=root
spring.datasource.password=Afiyabanu11#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=0